### ISSUE TITLE
UE <4.18  backward compatibility

### ISSUE THREAD

**Issue by Krzycho666** [xBazilio/UE4_Win_QtCreatorSourceCodeAccess#3]
After [updating](https://github.com/xBazilio/UE4_Win_QtCreatorSourceCodeAccess/commit/8c182a95543228a915733d666d23294a1be92b14) the plugin to UE 4.18 it doesn't work with older versions anymore. It's about OpenSolutionAtPath() and DoesSolutionExist() functions.

**Comment by xBazilio** [comment]
Hi, Krzycho666,
Do you mean older versions of Unreal Editor?
In the marketplace there are versions for 4.16, 4.17, and 4.18: https://www.unrealengine.com/marketplace/qt-creator-source-code-access
Can you attach an error you get?

**Comment by Krzycho666** [comment]
I'm working on custom engine, so I downloaded the master. I did some super fast adjustments using `#if ENGINE_MAJOR_VERSION >= 4 && ENGINE_MINOR_VERSION >= 18` here and there. I'll push it later if you want.

**Comment by xBazilio** [comment]
They have made some incompatable changes in UE 4.18. If your custom UE based on older versions you can download release from: https://github.com/xBazilio/UE4_Win_QtCreatorSourceCodeAccess/releases
  
Their marketplace system allows to keep older versions of plugins, so you do not need to check UE version in the code.

**Comment by Krzycho666** [comment]
Sure. But then the new updates won't be covered for older UE version.

**Comment by xBazilio** [comment]
I have made one new feature since version for UE 4.15. It is project files generating. But Qt Creator doesn't support settings import, so it works not as I wanted. For now all possible features for this code plugin are implemented. I only keep code up to date with UE API.
