### ISSUE TITLE
Add support for UE 4.20

### ISSUE THREAD

**Issue by silvanocerza** [xBazilio/UE4_Win_QtCreatorSourceCodeAccess#4]
Would be great if support for the version 4.20 could be added.

**Comment by xBazilio** [comment]
Sure! It would be great if I didn't have to upload new build with only version number changed. Or, at least, they notified me about new versions.

**Comment by xBazilio** [comment]
New release added, content submitted to Marketplace.

**Comment by xBazilio** [comment]
Ok. They have some problems compiling my upload. Will fix it and reupload.
I'll close this issue when they publish it to the marketplace.

But for now there is no problems for me to use this as a project plugin. It just works.

**Comment by xBazilio** [comment]
https://github.com/xBazilio/UE4_Win_QtCreatorSourceCodeAccess/releases/tag/3.3 should fix it. However I'm waiting for the marketplace support to compile and publish my new upload.

**Comment by xBazilio** [comment]
Just got an email about publishing.

**Comment by silvanocerza** [comment]
Great, thank you very much! :smile:
