### ISSUE TITLE
Mention to disable QtCreator 4.7 new clang based code model

### ISSUE THREAD

**Issue by kelteseth** [xBazilio/UE4_Win_QtCreatorSourceCodeAccess#6]
Hi,

The new replacement for the QtCreator code model/autocompletion is with the size of the Unreal Engine way to slow. Luckily the old code model is still available simply by disabling the clang code model via:

QtCreator  -> Help -> About Plugins -> c++ -> ClangCodeModel *//Disable the plugin and restart QtCreator

I think we should mention this somewhere in the readme :)

This is similar to this project/issue https://github.com/nibau/Unreal-Qt-project-generator/issues/6

**Comment by xBazilio** [comment]
Hi!
I think it does not relate to the plugin. It's about qt creator settings. Feel free to edit the wiki https://wiki.unrealengine.com/QtCreator_in_Windows and add this information yourself. This link is already in the Readme file.
